export const SAVE_USER = 'SAVE_USER';
export const SAVE_RECIPIENT_LISTS = 'SAVE_RECIPIENT_LISTS';
export const SAVE_SPENDING_EVENT_LISTS = 'SAVE_SPENDING_EVENT_LISTS';
export const SAVE_RECEIVED_EVENT_LISTS = 'SAVE_RECEIVED_EVENT_LISTS';
export const SAVE_TOTAL_SPENDING_MONEY = 'SAVE_TOTAL_SPENDING_MONEY';
export const SAVE_TOTAL_RECEIVED_MONEY = 'SAVE_TOTAL_RECEIVED_MONEY';
